server:
  port: 8000
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:mysql://localhost:3306/med?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 20
  application:
    name: REST-API Livraison a domicil
logging:
  level:
    web: debug
debug: true


security:
  jwt:
    token-signing-key: 9ed04ef5-b3cf-45f0-af94-39db3f70ba74
    access-token-exp-time: 30
    refresh-token-exp-time: 1440
    signature-algorithm: HS256
app.regex:
  username: "^(?!.*\\.\\.)(?!.*\\.$)[^\\W][\\w.]{8,32}"
  telephone: "^(\\+212|0)[5-7]{1}[0-9]{8}$"

