server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/med?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL55Dialect
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 20
  application:
    name: REST-API Livraison a domicil
logging:
  level:
    web: debug

app.regex:
  username: "^(?!.*\\.\\.)(?!.*\\.$)[^\\W][\\w.]{8,32}"
  telephone: "^(\\+212|0)[5-7]{1}[0-9]{8}$"
